name: dpa-every-minute

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 11-23 25 10 *'
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: dpa-query
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter lxml pandas numpy requests datetime
    - name: Scraping dpa data
      run: jupyter nbconvert --to notebook --execute "dpa_api_us-wahl.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
